kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-image-scan
  namespace: fleet-local
spec:
  repo: https://github.com/ibrokethecloud/fleet-image-test
  branch: main
  paths: 
  - image-scan-example
  imageScanInterval: 1m 
  clientSecretName: secret 
  # specify the commit pattern
  imageScanCommit:
    authorName: ibrokethecloud
    authorEmail: gaurav.mehta@suse.com
    messageTemplate: "update image"