apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
spec:
  selector:
    matchLabels:
      app: curl-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: curl-deployment
    spec:
      containers:
      - name: fleet-image-test
        image: v0.1.3 # {"$imagescan": "test-curl:tag"}
